package com.example.iPalControlInterface;

import java.util.HashMap;

public final class MotorIdDict {
	public static HashMap<String, Integer> MOTOR_ID_MAP;
	public static String[] LEFT_ARM_JOINT_NAMES;
	public static String[] RIGHT_ARM_JOINT_NAMES;
	
	static {
		// Motor ID map
		MOTOR_ID_MAP = new HashMap<String, Integer>();
		
		MOTOR_ID_MAP.put("ARM_ROTATION_RIGHT", 0x01);
		MOTOR_ID_MAP.put("ARM_SWING_RIGHT", 0x02);
		MOTOR_ID_MAP.put("FOREARM_ROTATION_RIGHT", 0x03);
		MOTOR_ID_MAP.put("FOREARM_SWING_RIGHT", 0x04);
		MOTOR_ID_MAP.put("WRIST_RIGHT", 0x05);

		MOTOR_ID_MAP.put("ARM_ROTATION_LEFT", 0x09);
		MOTOR_ID_MAP.put("ARM_SWING_LEFT", 0x0A);
		MOTOR_ID_MAP.put("FOREARM_ROTATION_LEFT", 0x0B);
		MOTOR_ID_MAP.put("FOREARM_SWING_LEFT", 0x0C);
		MOTOR_ID_MAP.put("WRIST_LEFT", 0x0D);

		MOTOR_ID_MAP.put("WAIST_TILT", 0x13);

		MOTOR_ID_MAP.put("NECK_ROTATION", 0x14);
		MOTOR_ID_MAP.put("NECK_TILT", 0x15);

		MOTOR_ID_MAP.put("WHEEL_LEFT", 0x18);
		MOTOR_ID_MAP.put("WHEEL_RIGHT", 0x19);

		MOTOR_ID_MAP.put("THUMB_RIGHT", 0x20);
		MOTOR_ID_MAP.put("FOREFINGER_RIGHT", 0x21);
		MOTOR_ID_MAP.put("MIDDLEFINGER_RIGHT", 0x22);
		MOTOR_ID_MAP.put("RINGFINGER_RIGHT", 0x23);
		MOTOR_ID_MAP.put("LITTLEFINGER_RIGHT", 0x24);
		MOTOR_ID_MAP.put("FOREFINGER_LEFT", 0x26);
		MOTOR_ID_MAP.put("MIDDLEFINGER_LEFT", 0x27);
		MOTOR_ID_MAP.put("RINGFINGER_LEFT", 0x28);
		MOTOR_ID_MAP.put("LITTLEFINGER_LEFT", 0x29);
		
		// Arm name Strings
		RIGHT_ARM_JOINT_NAMES = new String[] {"ARM_ROTATION_RIGHT", "ARM_SWING_RIGHT", "FOREARM_ROTATION_RIGHT", "FOREARM_SWING_RIGHT", "WRIST_RIGHT"};
		LEFT_ARM_JOINT_NAMES = new String[] {"ARM_ROTATION_LEFT", "ARM_SWING_LEFT", "FOREARM_ROTATION_LEFT", "FOREARM_SWING_LEFT", "WRIST_LEFT"};
	}
}
